export const ERROR_MESSAGES = {
  NOME_REQUERIDO: "O nome completo é obrigatório.",
  NOME_INVALIDO: "Por favor, digite seu nome completo (nome e sobrenome).",
  EMAIL_REQUERIDO: "O e-mail é obrigatório.",
  EMAIL_INVALIDO: "Digite um e-mail válido (ex: seu@email.com).",
  CPF_REQUERIDO: "O CPF é obrigatório.",
  CPF_INVALIDO: "Digite um CPF válido com 11 dígitos.",
  TELEFONE_REQUERIDO: "O telefone é obrigatório.",
  TELEFONE_INVALIDO: "Digite um telefone válido.",
  DATA_NASCIMENTO_REQUERIDA: "A data de nascimento é obrigatória.",
  DATA_NASCIMENTO_MENOR_18: "Você deve ter pelo menos 18 anos de idade para se cadastrar.",
  DATA_NASCIMENTO_FUTURA: "A data de nascimento não pode ser no futuro.",
  DATA_NASCIMENTO_INVALIDA: "Digite uma data de nascimento válida.",
  SENHA_REQUERIDA: "A senha é obrigatória.",
  SENHA_CURTA: "A senha deve ter pelo menos 6 caracteres.",
  CONFIRMAR_SENHA_REQUERIDA: "A confirmação da senha é obrigatória.",
  SENHAS_DIFERENTES: "As senhas não coincidem.",
  CEP_REQUERIDO: "O CEP é obrigatório.",
  CEP_INVALIDO: "Digite um CEP válido.",
  ENDERECO_REQUERIDO: "O endereço é obrigatório.",
  NUMERO_REQUERIDO: "O número é obrigatório.",
  BAIRRO_REQUERIDO: "O bairro é obrigatório.",
  CIDADE_REQUERIDA: "A cidade é obrigatória.",
  ESTADO_REQUERIDO: "O estado é obrigatório.",
  ESTADO_INVALIDO: "O estado deve ter 2 letras.",
  DOCUMENTO_FRENTE_REQUERIDO: "A imagem da frente do documento é obrigatória.",
  DOCUMENTO_VERSO_REQUERIDO: "A imagem do verso do documento é obrigatória.",
} as const;
